<?php

namespace Database\Seeders;

use App\Models\Movie;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MovieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movies = [
            [
                'tmdb_id' => 27205,
                'title' => 'Inception',
                'description' => 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
                'poster_path' => '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
                'rating' => 8.8,
                'genres' => ['Action', 'Science Fiction', 'Thriller'],
                'release_year' => 2010,
                'duration' => 148,
                'interpreter' => 'Christopher Nolan',
                'trailer_url' => 'https://www.youtube.com/watch?v=YoHD9XEInc0',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 155,
                'title' => 'The Dark Knight',
                'description' => 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
                'poster_path' => '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
                'rating' => 9.0,
                'genres' => ['Drama', 'Action', 'Crime', 'Thriller'],
                'release_year' => 2008,
                'duration' => 152,
                'interpreter' => 'Christopher Nolan',
                'trailer_url' => 'https://www.youtube.com/watch?v=EXeTwQWrcwY',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 680,
                'title' => 'Pulp Fiction',
                'description' => 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper.',
                'poster_path' => '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
                'rating' => 8.9,
                'genres' => ['Thriller', 'Crime'],
                'release_year' => 1994,
                'duration' => 154,
                'interpreter' => 'Quentin Tarantino',
                'trailer_url' => 'https://www.youtube.com/watch?v=s7EdQ4FqbhY',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 278,
                'title' => 'The Shawshank Redemption',
                'description' => 'Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison.',
                'poster_path' => '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
                'rating' => 9.3,
                'genres' => ['Drama', 'Crime'],
                'release_year' => 1994,
                'duration' => 142,
                'interpreter' => 'Frank Darabont',
                'trailer_url' => 'https://www.youtube.com/watch?v=6hB3S9bIaco',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 13,
                'title' => 'Forrest Gump',
                'description' => 'A man with a low IQ has accomplished great things in his life and been present during significant historic events.',
                'poster_path' => '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
                'rating' => 8.8,
                'genres' => ['Comedy', 'Drama', 'Romance'],
                'release_year' => 1994,
                'duration' => 142,
                'interpreter' => 'Robert Zemeckis',
                'trailer_url' => 'https://www.youtube.com/watch?v=bLvqoHBptjg',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 550,
                'title' => 'Fight Club',
                'description' => 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.',
                'poster_path' => '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
                'rating' => 8.4,
                'genres' => ['Drama'],
                'release_year' => 1999,
                'duration' => 139,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=SUXWAEX2jlg',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 603,
                'title' => 'The Matrix',
                'description' => 'A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.',
                'poster_path' => '/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
                'rating' => 8.7,
                'genres' => ['Action', 'Science Fiction'],
                'release_year' => 1999,
                'duration' => 136,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=vKQi3bBA1y8',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 762,
                'title' => 'Monty Python and the Holy Grail',
                'description' => 'King Arthur and his Knights of the Round Table embark on a surreal, low-budget search for the Holy Grail.',
                'poster_path' => '/8AVb7tyxZRsbKJNOTQJrrhh4T8P.jpg',
                'rating' => 8.0,
                'genres' => ['Comedy'],
                'release_year' => 1975,
                'duration' => 91,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=urRkGvhXc8w',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 769,
                'title' => 'GoodFellas',
                'description' => 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners.',
                'poster_path' => '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
                'rating' => 8.7,
                'genres' => ['Crime', 'Drama'],
                'release_year' => 1990,
                'duration' => 146,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=qo5jJpHtI1Y',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 862,
                'title' => 'Toy Story',
                'description' => 'A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy\'s room.',
                'poster_path' => '/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg',
                'rating' => 8.3,
                'genres' => ['Animation', 'Family'],
                'release_year' => 1995,
                'duration' => 81,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=KYz2wyBy3kc',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 105,
                'title' => 'Back to the Future',
                'description' => 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean.',
                'poster_path' => '/7lyBcpYB0Qt8gYhXYaEZUNlNQAv.jpg',
                'rating' => 8.3,
                'genres' => ['Adventure', 'Comedy', 'Science Fiction'],
                'release_year' => 1985,
                'duration' => 116,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=qvsgGtivCgs',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 120,
                'title' => 'The Lord of the Rings: The Fellowship of the Ring',
                'description' => 'A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring.',
                'poster_path' => '/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
                'rating' => 8.3,
                'genres' => ['Adventure', 'Fantasy'],
                'release_year' => 2001,
                'duration' => 178,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=V75dMMIW2B4',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 1726,
                'title' => 'Iron Man',
                'description' => 'After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.',
                'poster_path' => '/78lPtwv72eTNqFW9COBYI0dWDJa.jpg',
                'rating' => 7.6,
                'genres' => ['Action', 'Science Fiction', 'Adventure'],
                'release_year' => 2008,
                'duration' => 126,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=8ugaeA-nMTc',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 19995,
                'title' => 'Avatar',
                'description' => 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission.',
                'poster_path' => '/6EiRUJpuoeQPghrs3YNktfnqOVh.jpg',
                'rating' => 7.5,
                'genres' => ['Action', 'Adventure', 'Fantasy', 'Science Fiction'],
                'release_year' => 2009,
                'duration' => 162,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=5PSNL1qE6VY',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 694,
                'title' => 'The Shining',
                'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.',
                'poster_path' => '/9fgh3Ns1iRzlQNYuJyK0ARQZU7w.jpg',
                'rating' => 8.4,
                'genres' => ['Horror', 'Thriller'],
                'release_year' => 1980,
                'duration' => 146,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=5Cb3ik6zP2I',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
            [
                'tmdb_id' => 19404,
                'title' => 'Dilwale Dulhania Le Jayenge',
                'description' => 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh.',
                'poster_path' => '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
                'rating' => 8.7,
                'genres' => ['Comedy', 'Drama', 'Romance'],
                'release_year' => 1995,
                'duration' => 189,
                'interpreter' => null,
                'trailer_url' => 'https://www.youtube.com/watch?v=c25GKl5VNeY',
                'view_count' => 0,
                'is_deleted_for_users' => false,
            ],
        ];

        foreach ($movies as $movieData) {
            Movie::updateOrCreate(
                ['tmdb_id' => $movieData['tmdb_id']],
                $movieData
            );
        }
    }
}
